# Site settings
title: Robotics Summer Camp
email: camp@team3128.org
baseurl: "/camp" # the subpath of your site, e.g. /blog
url: "http://team3128.github.io" # the base hostname & protocol for your site
github_username:  team3128

# Build settings
markdown: kramdown

# Camp settings
priority_register_open_date_string: "March 7th"
general_register_open_date_string: "March 21st"
interest_form_url: "http://goo.gl/forms/CIlsKn9NTE"
volunteer_registration_form_url: "http://goo.gl/forms/qslncnCRCb"
