# Site settings
title: Robotics Summer Camp
email: camp@team3128.org
baseurl: "/camp" # the subpath of your site, e.g. /blog
url: "http://team3128.github.io" # the base hostname & protocol for your site
github_username:  team3128

# Build settings
markdown: kramdown

# Camp settings
priority_register_open_date_string: "March 7th"
general_register_open_date_string: "March 21st"
registration_open: true

date_range: "July 9th – August 3rd"

interest_form_url: "https://team3128.us17.list-manage.com/subscribe?u=7c13b1f47db9b4f3392eda9f2&id=34f1dbd104"

volunteer_registration_form_url: "http://goo.gl/forms/qslncnCRCb"
elementary_form_url: "http://www.sandiegonc.e2youngengineers.com/enrolment/"
lower_form_url: "https://fs30.formsite.com/ccaf/RoboticsSummerCamp56/index.html"
upper_form_url: "https://fs30.formsite.com/ccaf/RoboticsSummerCamp78/index.html"
waiting_list_url: "http://goo.gl/forms/FTRgMrwqX2"
